language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - mingw-w64
      - upx
      - musl
      - musl-dev
      - musl-tools

matrix:
  allow_failures:
    - rust: nightly
  include:
    - env:
      - TARGET=x86_64-unknown-linux-musl
      - BIN_NAME=dummyhttp
      - PROPER_NAME=dummyhttp-linux
      os: linux
    - env:
      - TARGET=x86_64-pc-windows-gnu
      - BIN_NAME=dummyhttp.exe
      - PROPER_NAME=dummyhttp-win.exe
      - RUSTFLAGS="-C linker=x86_64-w64-mingw32-gcc"
      os: linux
    - env:
      - TARGET=x86_64-apple-darwin
      - BIN_NAME=dummyhttp
      - PROPER_NAME=dummyhttp-osx
      os: osx

before_install:
  - rustup self update

install:
  # On Apple, the default target is already the right one.
  - if [[ -n $TARGET && $TARGET != "x86_64-apple-darwin" ]]; then rustup target add $TARGET; fi

script:
  # If this is a normal, non-deployment build...
  - if [[ -z $TARGET ]]; then cargo build --verbose; fi
  - if [[ -n $TARGET ]]; then cargo build --verbose --release --target $TARGET; fi

before_deploy:
  # If this is a binary deployment...
  - if [[ -n $TARGET ]]; then cp -a target/$TARGET/release/$BIN_NAME $PROPER_NAME && strip $PROPER_NAME; fi
  - # Run upx on the binary if this is a deployment for Linux or Windows
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then upx $PROPER_NAME; fi
  - if [[ $TARGET = "x86_64-unknown-linux-musl" ]]; then upx $PROPER_NAME; fi

deploy:
  - provider: releases
    api_key:
      secure: "fqz70rG/oWJBqkOJRt02bmpn9E+zZdaFsdie4vESZb6dOeB/9BLgd5blnoV8QKhtQ4UHCMjHXHyrZL6qjOvzSg7AbFXI1lDKzHggC4DsfEXKIEP8oKVBs5s/Bi2Ib1NquZ2qfKQwHdCGU0JtubuCN8ics+v6NZfCdiCkwES/zG9Uz9Z/FB9W8amknhxybcuamYJoB0vPTN0ZmCP4/7xuz00qbwskICxZrdu5Zw33a0zRPq98aqJiMdphflxsmxy7SRF0Z90QoTKQ5qfyd7SdgyJlvE4OuXeiXG7JvdqhKaKgdc7ko5qGunCi6+kgmDPehviHcZNXsGBRUkRA3GfChNgExjPyMewWxkkhAWiq0SU5+tYrdpOOAwKrvwXOXCtvtT3TvpmJYE4dSr5Ijsi1vQ5fqXLI8FiMYBUXIr9dqeucJPOvlPKlQBFK//hKr2lgadZ6zRPPkEFmuwrUAcTzMM+C/IYMf0ZMCehTkS/TW6KTqWA22IiwYjDDD6nXTo5mIy0AqVeyNwjoC6AiaDzjungtUZezO9U4Lm9UAUBNpoZdFCfPI2ilgMNz0QoxcVyiOWMIAa/E6dxB/9rKcBaH6mpXtshul7UFaxCRjpenOyLUw3PUW4TGsAgiqS5jF5yK3vR5MpCXj1/MazY8ykNkxZ0T8XcXqY+KV54ttTXa+2w="
    file: $PROPER_NAME
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_RUST_VERSION = stable && -n $TARGET
