[package]
name = "dummyhttp"
version = "0.1.0"
description = "Super simple HTTP server that replies a fixed body with a fixed response code"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
repository = "https://github.com/svenstaro/dummyhttp"
license = "MIT"
readme = "README.md"
keywords = ["dummy", "fake", "http-server", "http", "server"]
categories = ["command-line-utilities", "command-line-interface", "network-programming", "web-programming::http-server"]

[badges]
travis-ci = { repository = "svenstaro/dummyhttp", branch = "master" }
maintenance = { status = "actively-developed" }

[profile.release]
lto = true

[dependencies]
clap = "2.29"
actix-web = "0.6"
simplelog = "0.5"
